### ISSUE TITLE
Create gitter chat svg icon

### ISSUE THREAD

**Issue by rinse0ut** [CodeHubOrg/javascript101#103]
Create a chat icon for gitter with a speech bubble and the gitter pink colour and the vertical bars.

Basically transform this

https://github.com/CodeHubOrg/javascript101/blob/master/public/img/logo/gitter.png

to this svg layout:  

https://github.com/CodeHubOrg/javascript101/blob/master/public/img/icons/chat.svg

**Comment by trianah** [comment]
I don't create icons, but unless @paulfourniercarey does, I guess I could try copying and pasting two existing free icons to make it look like a chat icon?

**Comment by paulfourniercarey** [comment]
No problem I'll have a look tomorrow.

**Comment by paulfourniercarey** [comment]
![gitter-chat](https://cloud.githubusercontent.com/assets/4367728/26152618/87910f32-3aff-11e7-9ce5-b9986b9821b8.png)

Something like this, where is it for?

**Comment by rinse0ut** [comment]
@paulfourniercarey Spot on, it's for a fixed position chat icon that's displayed at the bottom right of the page.  Thanks.

**Comment by paulfourniercarey** [comment]
Ah, ok, the git chat box doesn’t allow svg files, see if it gets through
via email….




*Paul Fournier-Carey*
User Experience
Interface Design
Development Consultant

EPICreative Ltd

@twitpaul
lnked.in/paulfc

On 17 May 2017 at 12:58:25, Dave Thomson (notifications@github.com) wrote:

@paulfourniercarey <https://github.com/paulfourniercarey> Spot on, it's for
a fixed position chat icon that's displayed at the bottom right of the
page. Thanks.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/CodeHubOrg/javascript101/issues/103#issuecomment-302068192>,
or mute the thread

**Comment by paulfourniercarey** [comment]
Uploaded into icons folder
https://github.com/CodeHubOrg/javascript101/tree/master/public/img/icons

**Comment by katjad** [comment]
@paulfourniercarey That looks great, thank you!

**Comment by rinse0ut** [comment]
Nice works thanks.
